const actionType = {
  FETCH_ALL_TODOS: "FETCH_ALL_TODOS",
  CLEAR_COMPLETED_TODOS: "CLEAR_COMPLETED_TODOS",
  CREATE_NEW_TODO: "CREATE_NEW_TODO",
  ALL_ACTIVE_TODOS: "ALL_ACTIVE_TODOS",
  ALL_COMPLETED_TODOS: "ALL_COMPLETED_TODOS",
};

export default actionType;
